<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>AmbientTalk/2 Syntax: version 0.2</string>
	<key>fileTypes</key>
	<array>
		<string>at</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}</string>
	<key>keyEquivalent</key>
	<string></string>
	<key>name</key>
	<string>AmbientTalk 2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\s*deftype)\s+([a-zA-Z_?][a-zA-Z0-9_?]*)?\s*(&lt;:)?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.ambienttalk</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.ambienttalk</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.ambienttalk</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>meta.definition.type</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#canArguments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.ambienttalk</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.variable.ambienttalk</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\s*def)\s+([a-zA-Z_?][a-zA-Z0-9_?]*)?\s*(:=|;)</string>
			<key>name</key>
			<string>meta.definition.variable</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\s*def)\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.ambienttalk</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.definition.ambienttalk</string>
			<key>end</key>
			<string>\{|;</string>
			<key>name</key>
			<string>meta.definition.method</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#defCanonical</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#defKeyworded</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\s*def)\s+\[</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.ambienttalk</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.definition.ambienttalk</string>
			<key>end</key>
			<string>(\])</string>
			<key>name</key>
			<string>meta.definition.multiValue</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#canArguments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\s*def)\s+([a-zA-Z_?][a-zA-Z0-9_?]*)\[</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.ambienttalk</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.definition.ambienttalk</string>
			<key>end</key>
			<string>(\])</string>
			<key>name</key>
			<string>meta.definition.table</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant.numeric.ambienttalk</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ambienttalk</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@[a-zA-Z_?][a-zA-Z0-9_?]*)</string>
			<key>name</key>
			<string>meta.arguments.var-args.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.ambienttalk</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.ambienttalk</string>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ambienttalk</string>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.comment.block.ambienttalk</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(if|then|else|while|do|unless|foreach|in|raise|catch|using|let)+:</string>
			<key>name</key>
			<string>keyword.control.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(when|whenever|disconnected|reconnected|discovered|becomes|export|as)+:</string>
			<key>name</key>
			<string>keyword.async.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(import|exclude|alias)</string>
			<key>name</key>
			<string>keyword.scope.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(object|extend|with|share|clone|taggedAs|is|tagsOf)+:</string>
			<key>name</key>
			<string>keyword.objects.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(self|super)</string>
			<key>name</key>
			<string>keyword.objects.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(system|network|lobby|root|jlobby)</string>
			<key>name</key>
			<string>support.objects.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((mirror|reflect|mirroredBy)+:|defaultMirror)</string>
			<key>name</key>
			<string>support.mop.keywords.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(addMethod|clone|defineField|grabMethod|grabField|invoke|invokeField|listMethods|newInstance|print|respondsTo|select|isExtensionOfParent)\b(?=\()</string>
			<key>name</key>
			<string>support.mop.methods.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(base)\b</string>
			<key>name</key>
			<string>support.mop.fields.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|#|\$|%|&amp;|\*|\+|\-|/|\^|\\|~|\||&lt;|&gt;|=|:=)+</string>
			<key>name</key>
			<string>keyword.operator.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnew\b</string>
			<key>name</key>
			<string>keyword.operator.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(root|nil|true|false)\b|\b(super|self)\b(?=\()</string>
			<key>name</key>
			<string>constant.language.ambienttalk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round.ambienttalk</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>canArguments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ambienttalk</string>
				</dict>
			</dict>
			<key>matches</key>
			<string>(@[a-zA-Z_?][a-zA-Z0-9_?]*|[a-zA-Z_?][a-zA-Z0-9_?]*)</string>
		</dict>
		<key>defCanonical</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z_?][a-zA-Z0-9_?]*)\(</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ambienttalk</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#canArguments</string>
				</dict>
			</array>
		</dict>
		<key>defKeyworded</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ambienttalk</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z_?][a-zA-Z0-9_?]*+:)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ambienttalk2</string>
	<key>uuid</key>
	<string>A7894005-D8F2-449C-AC7E-EF04922A6D18</string>
</dict>
</plist>
